vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/images/posts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer